Obligatorio_MVC/Controllers/TIpoCabanaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Net.Http.Headers;
using Obligatorio_MVC.Models;
using Obligatorio_MVC.Servicios;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Microsoft.AspNetCore.Authorization;

namespace Obligatorio_MVC.Controllers
{
    [Authorize]
    public class TIpoCabanaController : Controller
    {

        private readonly ITipoCabanaService tipoCabanaService;

        public TIpoCabanaController(ITipoCabanaService tipoCabanaService)
        {
            this.tipoCabanaService = tipoCabanaService;
        }
        public IActionResult Index()
        {
            //string sesionUsuarioEmail = HttpContext.Session.GetString("SesionUsuario");
            //if (string.IsNullOrEmpty(sesionUsuarioEmail))
            //{
            //    return RedirectToAction("login", "Usuario");
            //}
            return View();
        }
        public IActionResult Privacy()
        {
            //string sesionUsuarioEmail = HttpContext.Session.GetString("SesionUsuario");
            //if (string.IsNullOrEmpty(sesionUsuarioEmail))
            //{
            //    return RedirectToAction("login", "Usuario");
            //}
            return View();
        }

        [HttpPost]
        [Route("TIpoCabana/Alta/{nombre}/{descripcion}/{CostoPorHuesped}")]
        public async Task<IActionResult> Alta(string nombre, string descripcion, int CostoPorHuesped)
        {
            var token = HttpContext.Session.GetString("AccessToken");
            IEnumerable<TipoCabanaModel> tipoCabanaModels = await tipoCabanaService.Alta(nombre, descripcion, CostoPorHuesped, token);
            return View();
        }

        [Route("TIpoCabana/ListarTipoCabana")]
        public async Task<IActionResult> ListarTipoCabana()
        {
            var token = HttpContext.Session.GetString("AccessToken");
            if (token == null)
            {
                // Manejar la situación, por ejemplo, redirigir al usuario al login
                return RedirectToAction("Login", "Usuario");
            }

            IEnumerable<TipoCabanaModel> tipoCabanaModels = await tipoCabanaService.ListarTipoCabana(token);
            return View(tipoCabanaModels);
        }


        [Route("TIpoCabana/BuscarTipoPorNombre/{nombre}")]
        public async Task<IActionResult> BuscarTipoPorNombre(string nombre)
        {

            var token = HttpContext.Session.GetString("AccessToken");
            IEnumerable<TipoCabanaModel> tipoCabanaModels = await tipoCabanaService.BuscarTipoPorNombre(nombre, token);
            return View("ListaDelaBusquedaPorNombre", tipoCabanaModels);
        }
    }

}

Obligatorio_MVC/Views/TipoCabana/Alta.cshtml
@model TipoCabanaModel
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h4>TipoCabana</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-controller="TipoCabana" asp-action="Alta" asp-route-nombre="Nombre" asp-route-descripcion="Descripcion" asp-route-CostoPorHuesped="CostoPorHuesped">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CostoPorHuesped" class="control-label"></label>
                <input type="number" asp-for="CostoPorHuesped" class="form-control" />
                <span asp-validation-for="CostoPorHuesped" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Obligatorio_MVC/Views/TipoCabana/BuscarTipoPorNombre.cshtml
@model TipoCabanaModel

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<form method="post" asp-controller="TIpoCabana" asp-action="BuscarTipoPorNombre" asp-route-nombre="nombre">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Nombre" class="control-label"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Buscar" class="btn btn-primary" />
    </div>
</form>

Obligatorio_MVC/Views/TipoCabana/ListaBusquedaPorNombreDelTipo.cshtml
@model IEnumerable<Obligatorio_MVC.Models.TipoCabanaModel>

@{
    ViewData["Title"] = "View";

}

<h1>View</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CostoPorHuesped)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdTipoCabana)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CostoPorHuesped)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdTipoCabana)
            </td>
@*            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>*@
        </tr>
}
    </tbody>
</table>

Obligatorio_MVC/Views/TipoCabana/ListaDelaBusquedaPorNombre.cshtml
@model IEnumerable<Obligatorio_MVC.Models.TipoCabanaModel>

@{
    ViewData["Title"] = "ListaDelaBusquedaPorNombre";

}

<h1>ListaDelaBusquedaPorNombre</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CostoPorHuesped)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdTipoCabana)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CostoPorHuesped)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdTipoCabana)
            </td>
@*            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>*@
        </tr>
}
    </tbody>
</table>

Obligatorio_MVC/Views/TipoCabana/ListarTipoCabana.cshtml
@model IEnumerable<TipoCabanaModel>

@{
    ViewData["Title"] = "ListarTipoCabana";
}

<h1>ListarTipoCabana</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CostoPorHuesped)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdTipoCabana)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CostoPorHuesped)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdTipoCabana)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>