Obligatorio_MVC/Controllers/CabanaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Net.Http.Headers;
using Obligatorio_MVC.Models;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Obligatorio_MVC.Controllers
{
    [Authorize]

    public class CabanaController : Controller
    {

        private readonly ICabanaService cabanaService; 





        public CabanaController(ICabanaService cabanaService)
        {
            this.cabanaService = cabanaService;
        }

        public async Task <IActionResult> Index()
        {
            //string sesionUsuarioEmail = HttpContext.Session.GetString("SesionUsuario");
            //if (string.IsNullOrEmpty(sesionUsuarioEmail))
            //{
            //    return RedirectToAction("login", "Usuario");
            //}
            IEnumerable<CabanaModel> cabanaModels = await cabanaService.ObtenerTodas();
            return View(cabanaModels);
        }
        public IActionResult AltaCabana()
        {
            //string sesionUsuarioEmail = HttpContext.Session.GetString("SesionUsuario");
            //if (string.IsNullOrEmpty(sesionUsuarioEmail))
            //{
            //    return RedirectToAction("login", "Usuario");
            //}
            return View();
        }
        [HttpPost]
        public IActionResult AltaCabana(string nombre, string descripcion, bool jacuzziPrivado, bool habilitadaReservas, int numeroHabitacion, int capacidadMaxima, IFormFile imagen, TipoCabanaModel tipoCabana, List<MantenimientoModel> listaMantenimiento)
        {
            //GuardarImagen(imagen, nombre, out string nombreResultante);
            //var nuevacabana = new Cabana()
            //{
            //    Nombre = nombre,
            //    Descripcion = descripcion,
            //    JacuzziPrivado = jacuzziPrivado,
            //    HabilitadaReservas = habilitadaReservas,
            //    NumeroHabitacion = numeroHabitacion,
            //    CapacidadMaxima = capacidadMaxima,
            //    Imagen = nombreResultante,
            //    TipoCabana = tipoCabana
            //};
            //if (nuevacabana.Validar())
            //{
            //    _cabanaRepositorio.Agregar(nuevacabana);
            //}
            //return RedirectToAction("Index", "Home");
            return View();
        }

        //private bool GuardarImagen(IFormFile imagen, string nombreCabana, out string nombreResultante)
        //{

        //    if (imagen is null || string.IsNullOrEmpty(nombreCabana))
        //    {
        //        nombreResultante = string.Empty;
        //        return false;
        //    }

        //    string rutaFisicaWwwRoot = _environment.WebRootPath;
        //    string nombreImagen = nombreCabana;
        //    string fileExtension = Path.GetExtension(imagen.FileName); if (fileExtension != ".png" && fileExtension != ".jpg") { TempData["Error"] = "La imagen no es valida"; nombreResultante = string.Empty; return false; }
        //    string rutaFisicaFoto = Path.Combine(rutaFisicaWwwRoot, "imagenes", "fotos", nombreImagen + fileExtension);

        //    try
        //    {
        //        using (FileStream f = new FileStream(rutaFisicaFoto, FileMode.Create))
        //        {
        //            imagen.CopyTo(f);
        //        }
        //        nombreResultante = nombreImagen + fileExtension;
        //        return true;
        //    }
        //    catch (Exception)
        //    {
        //        nombreResultante = string.Empty;
        //        return false;
        //    }
        //    return true;
        //}


        [Route("Cabana/BuscarCabanas")]
        public async Task<IActionResult> BuscarCabanas()
        {
            var token = HttpContext.Session.GetString("AccessToken");
            IEnumerable<CabanaModel> cabanaModels = await cabanaService.BuscarCabanas(token);
            return View(cabanaModels);
        }

        [Route("Cabana/BuscarCabanaPorNombre/{nombre}")]
        public async Task<IActionResult> BuscarCabanaPorNombre(string nombre)
        {

            var token = HttpContext.Session.GetString("AccessToken");
            IEnumerable<CabanaModel> cabanaModels = await cabanaService.BuscarPorNombre(nombre, token);
            return View(cabanaModels);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> BuscarCabanaPorNombrePost(string nombre)
        {
            var token = HttpContext.Session.GetString("AccessToken");
            IEnumerable<CabanaModel> cabanaModels = await cabanaService.BuscarPorNombre(nombre, token);
            return View(cabanaModels);
        }


        [Route("Cabana/BuscarCabanaPorTipo/{tipo}")]
        public async Task<IActionResult> BuscarCabanaPorTipo(string tipo)
        {

            var token = HttpContext.Session.GetString("AccessToken");
            IEnumerable<CabanaModel> cabanaModels = await cabanaService.BuscarCabanaPorTipo(tipo, token);
            return View(cabanaModels);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BuscarCabanaPorTipoPost(string tipo)
        {
            var token = HttpContext.Session.GetString("AccessToken");
            IEnumerable<CabanaModel> cabanaModels = await cabanaService.BuscarCabanaPorTipo(tipo, token);
            return View(cabanaModels);
        }


        [Route("Cabana/BuscarCabanaPorCantidadMaximaDePersonas/{maxpersonas}")]
        public async Task<IActionResult> BuscarCabanaPorCantidadMaximaDePersonas(int maxpersonas)
        {
            var token = HttpContext.Session.GetString("AccessToken");
            IEnumerable<CabanaModel> cabanaModels = await cabanaService.BuscarCabanaPorCantidadMaximaDePersonas(maxpersonas, token);
            return View(cabanaModels);
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BuscarCabanaPorCantidadMaximaDePersonasPost(int maxpersonas)
        {
            var token = HttpContext.Session.GetString("AccessToken");
            IEnumerable<CabanaModel> cabanaModels = await cabanaService.BuscarCabanaPorCantidadMaximaDePersonas(maxpersonas, token);
            return View(cabanaModels);
        }


        [Route("Cabana/BuscarCabanasHabilitadas")]
        public async Task<IActionResult>  BuscarCabanasHabilitadas()
        {
            var token = HttpContext.Session.GetString("AccessToken");
            IEnumerable<CabanaModel> cabanaModels = await cabanaService.BuscarCabanasHabilitadas(token);
            return View(cabanaModels);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BuscarCabanasHabilitadasPost()
        {
            var token = HttpContext.Session.GetString("AccessToken");
            IEnumerable<CabanaModel> cabanaModels = await cabanaService.BuscarCabanasHabilitadas(token);
            return View(cabanaModels);
        }




        [Route("Cabana/BuscarTodas")]
        public async Task<ActionResult> BuscarTodas()
        {
            var token = HttpContext.Session.GetString("AccessToken");
            IEnumerable<CabanaModel> cabanaModels = await cabanaService.BuscarTodas(token);
           return View(cabanaModels);


        }

        [HttpPost]
        public async Task<IActionResult> BuscarPorTipoyMonto(ParaBuscarPorTipoyMontoModel model)
        {
            var token = HttpContext.Session.GetString("AccessToken");

            IEnumerable<CabanaModel> cabanaModels = await cabanaService.BuscarPorTipoyMonto(model, token);
            return View(cabanaModels);
        }
        [HttpPost]
        public async Task<IActionResult> BusquedaCapacidad(int min, int max)
        {
            var token = HttpContext.Session.GetString("AccessToken");

            IEnumerable<CabanaModel> cabanaModels = await cabanaService.BusquedaCapacidad(min, max , token);
            return View(cabanaModels);
        }
        
    }
}

Obligatorio_MVC/Controllers/MantenimientoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Net.Http.Headers;
using Obligatorio_MVC.Models;
using Obligatorio_MVC.Servicios;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Microsoft.AspNetCore.Authorization;

namespace Obligatorio_MVC.Controllers
{
    [Authorize]
    public class MantenimientoController : Controller
    {
        private readonly IMantenimientoService mantenimientoService;

        public MantenimientoController(IMantenimientoService mantenimientoService)
        {
            this.mantenimientoService = mantenimientoService;
        }

        public IActionResult Index()
        {
            //string sesionUsuarioEmail = HttpContext.Session.GetString("SesionUsuario");
            //if (string.IsNullOrEmpty(sesionUsuarioEmail))
            //{
            //    return RedirectToAction("login", "Usuario");
            //}

            return View();
        }



        [HttpPost]
        [Route("Mantenimiento/BuscarMantenimientoEntreFechas")]
        public async Task<IActionResult> BuscarMantenimientoEntreFechas(BuscarMantenimientoRequest request)
        {
            var token = HttpContext.Session.GetString("AccessToken");

            IEnumerable<MantenimientoModel> mantenimientoModels = await mantenimientoService.BuscarMantenimientoEntreFechas(request.Id, request.FechaInicio, request.FechaFin, token);
            return View("ListaBuscarMantenimientoEntreFechas", mantenimientoModels);
        }


        [HttpPost]
        [Route("Mantenimiento/RegistroMantenimiento")]
        public async Task<IActionResult> RegistroMantenimiento(RegistroMantenimientoModel request)
        {
            var token = HttpContext.Session.GetString("AccessToken");
            IEnumerable<MantenimientoModel> mantenimientoModels = await mantenimientoService.RegistroMantenimiento(request.Id, request.Fecha, request.costo, request.descripcion, request.trabajador, token);
            return View("ListarRegistroMantenimiento", mantenimientoModels);
        }

    }
}

Obligatorio_MVC/Views/Cabana/AltaCabana.cshtml
@model IEnumerable<CabanaModel>

@{
    ViewData["Title"] = "AltaCabana";
}

<h1>AltaCabana</h1>

<h4>Cabana</h4>
<hr />
<div class="row">
    <div class="col-md-4">
@*        <form asp-action="AltaCabana" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="JacuzziPrivado" /> @Html.DisplayNameFor(model => model.JacuzziPrivado)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HabilitadaReservas" /> @Html.DisplayNameFor(model => model.HabilitadaReservas)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="NumeroHabitacion" class="control-label"></label>
                <input asp-for="NumeroHabitacion" class="form-control" />
                <span asp-validation-for="NumeroHabitacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CapacidadMaxima" class="control-label"></label>
                <input asp-for="CapacidadMaxima" class="form-control" />
                <span asp-validation-for="CapacidadMaxima" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="imagen" class="control-label"></label>
                <input type="file" name="imagen" class="form-control" />
                <span asp-validation="imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>*@
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Obligatorio_MVC/Views/Cabana/BuscarCabanaPorCantidadMaximaDePersonas.cshtml
@model IEnumerable<CabanaModel>

@{
    ViewData["Title"] = "BuscarCabanaPorCantidadMaximaDePersonas";
}

<h1>BuscarCabanaPorCantidadMaximaDePersonas</h1>
@if (TempData.ContainsKey("ErrorBuscarCabanaNombre"))
{
    <div class="alert alert-danger" role="alert">
        @TempData["ErrorBuscarCabanaNombre"]
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JacuzziPrivado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HabilitadaReservas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroHabitacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CapacidadMaxima)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JacuzziPrivado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HabilitadaReservas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroHabitacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CapacidadMaxima)
            </td>
            <td>

                    <img class="img-thumbnail" src="~/imagenes/fotos/@item.Imagen" />
            </td>

        </tr>
}
    </tbody>
</table>

Obligatorio_MVC/Views/Cabana/BuscarCabanaPorCantidadMaximaDePersonasPost.cshtml
@model IEnumerable<Obligatorio_MVC.Models.CabanaModel>

@{
    ViewData["Title"] = "BuscarCabanaPorCantidadMaximaDePersonasPost";
}

<h1>BuscarCabanaPorCantidadMaximaDePersonasPost</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JacuzziPrivado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HabilitadaReservas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroHabitacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CapacidadMaxima)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JacuzziPrivado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HabilitadaReservas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroHabitacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CapacidadMaxima)
            </td>
                <td>

                    <img class="img-thumbnail" src="~/imagenes/fotos/@item.Imagen" />
                </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Obligatorio_MVC/Views/Cabana/BuscarCabanaPorNombrePost.cshtml
@model IEnumerable<Obligatorio_MVC.Models.CabanaModel>

@{
    ViewData["Title"] = "BuscarCabanaPorNombrePost";
}

<h1>BuscarCabanaPorNombrePost</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JacuzziPrivado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HabilitadaReservas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroHabitacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CapacidadMaxima)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JacuzziPrivado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HabilitadaReservas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroHabitacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CapacidadMaxima)
                </td>
                <td>

                    <img class="img-thumbnail" src="~/imagenes/fotos/@item.Imagen" />
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>

Obligatorio_MVC/Views/Cabana/BuscarCabanaPorTipo.cshtml
@model IEnumerable<CabanaModel>

@{
    ViewData["Title"] = "BuscarCabanaPorTipo";
}

<h1>BuscarCabanaPorTipo</h1>
@if (TempData.ContainsKey("ErrorBuscarCabanaNombre"))
{
    <div class="alert alert-danger" role="alert">
        @TempData["ErrorBuscarCabanaNombre"]
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JacuzziPrivado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HabilitadaReservas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroHabitacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CapacidadMaxima)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JacuzziPrivado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HabilitadaReservas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroHabitacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CapacidadMaxima)
            </td>
            <td>

                    <img class="img-thumbnail" src="~/imagenes/fotos/@item.Imagen" />
            </td>

        </tr>
}
    </tbody>
</table>

Obligatorio_MVC/Views/Cabana/BuscarCabanaPorTipoPost.cshtml
@model IEnumerable<Obligatorio_MVC.Models.CabanaModel>

@{
    ViewData["Title"] = "BuscarCabanaPorTipoPost";
}

<h1>BuscarCabanaPorTipoPost</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JacuzziPrivado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HabilitadaReservas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroHabitacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CapacidadMaxima)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JacuzziPrivado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HabilitadaReservas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroHabitacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CapacidadMaxima)
                </td>
                <td>

                    <img class="img-thumbnail" src="~/imagenes/fotos/@item.Imagen" />
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>

Obligatorio_MVC/Views/Cabana/BuscarCabanas.cshtml
@model IEnumerable<CabanaModel>

<form method="post" asp-action="BuscarCabanaPorNombrePost">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="nombre">Busqueda por Nombre:</label>
        <input type="text" class="form-control" name="nombre" id="nombre" required>
    </div>
    <button type="submit" class="btn btn-primary">Buscar</button>
</form>
<form method="post" asp-action="BuscarCabanaPorTipoPost">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="nombre">Busqueda por Tipo:</label>
        <input type="text" class="form-control" name="tipo" id="tipo" required>
    </div>
    <button type="submit" class="btn btn-primary">Buscar</button>
</form>

<form method="post" asp-action="BuscarCabanaPorCantidadMaximaDePersonasPost">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="nombre">Busqueda por cantidad maxima de personas:</label>
        <input type="number" class="form-control" name="maxpersonas" id="maxpersonas" required>
    </div>
    <button type="submit" class="btn btn-primary">Buscar</button>

</form>

<form method="post" asp-action="BuscarCabanasHabilitadasPost">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="nombre">Busqueda de  cabanas habilitadas:</label>

    </div>
    <button type="submit" class="btn btn-primary">Buscar</button>

</form>

<form method="post" asp-action="BuscarTodas">
    <div class="form-group">
        <label for="nombre">Todas las cabanas:</label>

    </div>
    <button type="submit" class="btn btn-primary">Buscar</button>

</form>

Obligatorio_MVC/Views/Cabana/BuscarTodas.cshtml
@model IEnumerable<CabanaModel>

@{
    ViewData["Title"] = "BuscarTodas";
}

<h1>BuscarTodas</h1>
@if (TempData.ContainsKey("ErrorBuscarCabanaNombre"))
{
    <div class="alert alert-danger" role="alert">
        @TempData["ErrorBuscarCabanaNombre"]
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JacuzziPrivado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HabilitadaReservas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroHabitacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CapacidadMaxima)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Any())
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.JacuzziPrivado)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HabilitadaReservas)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumeroHabitacion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CapacidadMaxima)
                    </td>
                    <td>

                        <img class="img-thumbnail" src="~/imagenes/fotos/@item.Imagen" />
                    </td>
@*                    <td>

                        <a asp-controller="Mantenimiento" asp-action="BuscarMantenimientoEntreFechasController" asp-route-id="@item.NumeroHabitacion">Mantenimiento</a>
                        <a asp-controller="Mantenimiento" asp-action="RegistroMantenimiento" asp-route-id="@item.NumeroHabitacion">Registro de nuevo mantenimiento</a>
                    </td>*@
                </tr>
            }
        }
        else
        {
            <tr>
                <td> Error, no hay resultados </td>
            </tr>
        }
    </tbody>
</table>

Obligatorio_MVC/Views/Cabana/FormParaBusquedaCapacidad.cshtml
@model Obligatorio_MVC.Models.ModelParaBusquedaCapacidad

<h1>FormParaBuscarPorTipoyMonto</h1>

<h4>CabanaModel</h4>
<hr />
<form method="post" asp-controller="Cabana" asp-action="BusquedaCapacidad">
    <div class="form-group">
        <label for="monto">min:</label>
        <input type="number" name="min" class="form-control" placeholder="min">
    </div>
    <div class="form-group">
        <label for="monto">max:</label>
        <input type="number" name="max" class="form-control" placeholder="max">
    </div>
    <button type="submit" class="btn btn-primary">Buscar</button>
</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Obligatorio_MVC/Views/Cabana/Index.cshtml
@model IEnumerable<CabanaModel>
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

@{
   
}